### ISSUE TITLE
Wrong value?

### ISSUE THREAD

**Issue by jumpjack** [TrystanLea/SAPjs#1]
Shouldn't this value be filled automatically?

![image](https://user-images.githubusercontent.com/1620953/194533510-d0a2eca0-f1d2-426e-94a3-da4a2075b08e.png)

**Comment by TrystanLea** [comment]
Hello @jumpjack the living area can be a different area to the total building area. E.g a utility room or garage may not be included in the total floor area. The model calculates  two sets of internal temperature one for the living area and another for the whole dwelling, a smaller living area reduces heat demand if that's how the space is used..
